// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearAllClipboardItems(arg1) {
  return window['go']['main']['App']['ClearAllClipboardItems'](arg1);
}

export function ClearClipboardItemsByType(arg1, arg2) {
  return window['go']['main']['App']['ClearClipboardItemsByType'](arg1, arg2);
}

export function DeleteClipboardItem(arg1) {
  return window['go']['main']['App']['DeleteClipboardItem'](arg1);
}

export function GetClipboardItemByID(arg1) {
  return window['go']['main']['App']['GetClipboardItemByID'](arg1);
}

export function GetClipboardItems(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetClipboardItems'](arg1, arg2, arg3);
}

export function GetMonitoringStatus() {
  return window['go']['main']['App']['GetMonitoringStatus']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function HideSearchInterface() {
  return window['go']['main']['App']['HideSearchInterface']();
}

export function IsMonitoringEnabled() {
  return window['go']['main']['App']['IsMonitoringEnabled']();
}

export function PinClipboardItem(arg1, arg2) {
  return window['go']['main']['App']['PinClipboardItem'](arg1, arg2);
}

export function SearchClipboardItems(arg1, arg2) {
  return window['go']['main']['App']['SearchClipboardItems'](arg1, arg2);
}

export function SearchClipboardItemsRegex(arg1, arg2) {
  return window['go']['main']['App']['SearchClipboardItemsRegex'](arg1, arg2);
}

export function SelectClipboardItem(arg1) {
  return window['go']['main']['App']['SelectClipboardItem'](arg1);
}

export function ShowSearchInterface() {
  return window['go']['main']['App']['ShowSearchInterface']();
}

export function ToggleMonitoring() {
  return window['go']['main']['App']['ToggleMonitoring']();
}

export function TriggerGlobalHotkey() {
  return window['go']['main']['App']['TriggerGlobalHotkey']();
}

export function UpdateSettings(arg1) {
  return window['go']['main']['App']['UpdateSettings'](arg1);
}
