// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function ClearAllClipboardItems(arg1:boolean):Promise<void>;

export function ClearClipboardItemsByType(arg1:string,arg2:boolean):Promise<void>;

export function DeleteClipboardItem(arg1:string):Promise<void>;

export function GetClipboardItemByID(arg1:string):Promise<models.ClipboardItem>;

export function GetClipboardItems(arg1:number,arg2:number,arg3:string):Promise<Array<models.ClipboardItem>>;

export function GetClipboardItemsPaginated(arg1:number,arg2:number,arg3:string):Promise<Array<models.ClipboardItem>>;

export function GetMonitoringStatus():Promise<Record<string, any>>;

export function GetSettings():Promise<models.Settings>;

export function HideSearchInterface():Promise<void>;

export function IsMonitoringEnabled():Promise<boolean>;

export function PinClipboardItem(arg1:string,arg2:boolean):Promise<void>;

export function SearchClipboardItems(arg1:string,arg2:number):Promise<Array<models.ClipboardItem>>;

export function SearchClipboardItemsPaginated(arg1:string,arg2:number,arg3:number,arg4:boolean):Promise<Array<models.ClipboardItem>>;

export function SearchClipboardItemsRegex(arg1:string,arg2:number):Promise<Array<models.ClipboardItem>>;

export function SelectClipboardItem(arg1:string):Promise<void>;

export function ShowSearchInterface():Promise<void>;

export function ToggleMonitoring():Promise<boolean>;

export function TriggerGlobalHotkey():Promise<void>;

export function UpdateSettings(arg1:models.Settings):Promise<void>;
